/**
 * .aiignore template generator.
 * Returns framework-specific ignore patterns to prevent AI agents
 * from indexing build artifacts, dependencies, and generated files.
 */

// ─── Common patterns (always included) ───────────────────────────────────────
const COMMON = `
# ── OS & Editor ──
.DS_Store
Thumbs.db
*.swp
*.swo
*.log

# ── Version Control ──
.git/

# ── Lock Files ──
*.lock
package-lock.json
yarn.lock
pnpm-lock.yaml
`.trim();

// ─── Framework-specific patterns ─────────────────────────────────────────────
const FRAMEWORK_PATTERNS = {
    flutter: `
# ── Flutter / Dart ──
.dart_tool/
.packages
build/
.flutter-plugins
.flutter-plugins-dependencies
*.iml
.idea/
ios/Pods/
ios/.symlinks/
ios/Flutter/Flutter.framework
ios/Flutter/Flutter.podspec
android/.gradle/
android/local.properties
android/app/build/
android/build/
.pub-cache/
.pub/
coverage/
`,

    laravel: `
# ── Laravel / PHP ──
vendor/
node_modules/
storage/framework/
storage/logs/
bootstrap/cache/
public/hot
public/storage
.env
.env.backup
.phpunit.result.cache
Homestead.yaml
Homestead.json
npm-debug.log
`,

    react: `
# ── React / Next.js ──
node_modules/
.next/
out/
build/
dist/
coverage/
.env.local
.env.*.local
.vercel/
.turbo/
storybook-static/
`,

    nodejs: `
# ── Node.js / Express ──
node_modules/
dist/
build/
coverage/
.env
.env.*
*.tsbuildinfo
`,

    python: `
# ── Python / Django ──
__pycache__/
*.py[cod]
*.so
.venv/
venv/
env/
.env
*.egg-info/
dist/
build/
.mypy_cache/
.pytest_cache/
htmlcov/
migrations/
db.sqlite3
`,

    other: `
# ── General Build ──
node_modules/
dist/
build/
coverage/
.env
`,
};

/**
 * Generate .aiignore content for a given framework.
 * @param {string} framework - One of: flutter, laravel, react, nodejs, python, other
 * @returns {string} Full .aiignore file content
 */
export function getAiIgnore(framework) {
    const key = framework.toLowerCase();
    const specific = FRAMEWORK_PATTERNS[key] || FRAMEWORK_PATTERNS.other;

    return `# ═══════════════════════════════════════════════════════════════════════════════
# .aiignore — Auto-generated by init-antigravity-workflow
# Framework: ${framework}
# Prevents AI agents from indexing build artifacts & dependencies.
# ═══════════════════════════════════════════════════════════════════════════════

${COMMON}

${specific.trim()}
`;
}
