/**
 * init-antigravity-workflow-context-engine — Clean Command
 *
 * Removes all files and directories generated by the `init` command.
 * Supports interactive confirmation and a --force flag to skip prompts.
 */

import { confirm } from '@inquirer/prompts';
import chalk from 'chalk';
import { existsSync, readdirSync, unlinkSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';

// Files/dirs that init can generate
const ANTIGRAVITY_DIR = '.antigravity';

const GENERATED_FILES = [
    '.aiignore',
    '.agentrules',
    '.cursorrules',
];

/**
 * Discover all files/dirs created by init in the given working directory.
 * @returns {{ files: string[], dirs: string[] }}
 */
function discoverGenerated(cwd) {
    const files = [];
    const dirs = [];

    // Check top-level generated files
    for (const file of GENERATED_FILES) {
        const fullPath = join(cwd, file);
        if (existsSync(fullPath)) {
            files.push(file);
        }
    }

    // Check .antigravity/ directory
    const antigravDir = join(cwd, ANTIGRAVITY_DIR);
    if (existsSync(antigravDir) && statSync(antigravDir).isDirectory()) {
        const contents = readdirSync(antigravDir);
        contents.forEach(f => files.push(`${ANTIGRAVITY_DIR}/${f}`));
        dirs.push(ANTIGRAVITY_DIR);
    }

    return { files, dirs };
}

/**
 * Run the clean command.
 * @param {{ force?: boolean }} options
 */
export async function clean(options = {}) {
    const cwd = process.cwd();
    const force = options.force || false;

    // ── Banner ──
    console.log('');
    console.log(chalk.bgRed.white.bold('                                                        '));
    console.log(chalk.bgRed.white.bold('   🧹  init-antigravity-workflow  clean                 '));
    console.log(chalk.bgRed.white.bold('   AI Context Engine Edition                             '));
    console.log(chalk.bgRed.white.bold('   Remove all generated workflow files                   '));
    console.log(chalk.bgRed.white.bold('                                                        '));
    console.log('');
    console.log(chalk.dim(`  Working directory: ${cwd}`));
    console.log('');

    // ── Discover ──
    const { files, dirs } = discoverGenerated(cwd);

    if (files.length === 0 && dirs.length === 0) {
        console.log(chalk.yellow('  ⚠  No generated files found. Nothing to clean.'));
        console.log('');
        return;
    }

    // ── Show what will be removed ──
    console.log(chalk.white.bold('  The following files/directories will be removed:'));
    console.log('');
    for (const file of files) {
        console.log(chalk.red(`    ✗  ${file}`));
    }
    console.log('');

    // ── Confirm ──
    if (!force) {
        const proceed = await confirm({
            message: 'Are you sure you want to remove all generated files? This cannot be undone.',
            default: false,
        });

        if (!proceed) {
            console.log(chalk.yellow('\n  Aborted. No files were removed.\n'));
            return;
        }
    }

    // ── Remove files ──
    console.log('');

    // Remove .antigravity/ directory (and all contents)
    for (const dir of dirs) {
        const dirPath = join(cwd, dir);
        if (existsSync(dirPath)) {
            rmSync(dirPath, { recursive: true, force: true });
            console.log(chalk.red(`  ✗  Removed: ${dir}/  (and all contents)`));
        }
    }

    // Remove top-level generated files
    for (const file of GENERATED_FILES) {
        const fullPath = join(cwd, file);
        if (existsSync(fullPath)) {
            unlinkSync(fullPath);
            console.log(chalk.red(`  ✗  Removed: ${file}`));
        }
    }

    // ── Done ──
    console.log('');
    console.log(chalk.green.bold('  ✅ Clean complete. All generated files have been removed.'));
    console.log(chalk.dim('  Run `npx init-antigravity-workflow-context-engine` to re-initialize.'));
    console.log('');
}
